catalog:
  '@antfu/eslint-config': 6.4.1
  '@gitbeaker/rest': ^43.8.0
  '@types/node': 24.10.1
  bumpp: ^10.3.2
  cac: ^6.7.14
  eslint: 9.39.1
  eslint-plugin-format: 1.1.0
  express: ^5.2.1
  tsdown: ^0.17.2
  typescript: ^5.9.3
  yaml: ^2.8.2

catalogMode: strict

cleanupUnusedCatalogs: true

shellEmulator: true
