catalog:
  '@antfu/eslint-config': ^6.4.1
  '@fastify/cors': ^11.2.0
  '@gitbeaker/rest': ^43.8.0
  '@types/node': ^24.10.1
  cac: ^6.7.14
  dotenv: ^17.2.3
  eslint: ^9.39.1
  eslint-plugin-format: ^1.1.0
  execa: ^9.6.1
  fastify: ^5.6.2
  pino: ^10.1.0
  pino-pretty: ^13.1.3
  tsdown: ^0.17.2
  typescript: ~5.9.3
  yaml: ^2.8.2

catalogMode: strict

cleanupUnusedCatalogs: true

shellEmulator: true
